version: "2"

linters:
  enable:
    - exhaustruct

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (github.com/spf13/afero.File).Close

  exclusions:
    paths:
      - build/.*
