name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          install-only: true

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.pnpm-store
          key: ${{ runner.os }}-deps-${{ hashFiles('**/go.sum', '**/pnpm-lock.yaml') }}

      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libgtk-4-dev libwebkitgtk-6.0-dev just libmpv-dev

      - run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - run: just ci
