name: format code

on: 
  push: 
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version-file: "go.mod"
          cache-dependency-path: "**/go.sum"

      - name: Run formatters
        run: "go fmt"

      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "formatters: ran formatters"
